from fields import *

# Paths
OUTPUT_DIR = "output"

FILE_NAME = "JP_ETFs.csv"
# FILE_NAME = "JP_ETFs_full.csv"
# FILE_NAME = "JP_stocks.csv"
# FILE_NAME = "US_stocks.csv"
# FILE_NAME = "HK_stocks.csv"

SPEED = NORMAL
# SPEED = FAST

MODE = UPDATE_FINANCIALS
# MODE = FILTER_ETFS

# Batch Configurations
BATCH_SIZE = 39
TV_SLEEP_LOOKUP = [
  (100, (25, 40)),
  (300, (30, 45)),
  (600, (35, 50)),
  (float("inf"), (45, 60))
]

# Column Configurations
COLUMNS_TO_PRESERVE = [TICKER, FEE, BOUGHT, NOTE]

FINAL_COLUMNS = [
  TICKER, NAME,
  FEE, BOUGHT,
  ROA, NET_MARGIN, OPERATING_MARGIN, DEBT_TO_EQUITY, EARNINGS_GROWTH,
  VOL_1D, VOL_3D, VOL_5D, VOL_30D,
  DIVIDEND_YIELD,
  AVG_VOLUME,
  MARKET_CAP,
  PE_RATIO, FORWARD_PE_RATIO, PB,
  PRICE_1D, PRICE_3D, PRICE_5D, PRICE_7D, PRICE_30D,
  TARGET_HIGH_PERCENT, TARGET_LOW_PERCENT, TARGET_MEAN_PERCENT,
  CURRENT_PRICE,
  AVG_RATING_1D, AVG_RATING_7D, # AVG_RATING_1M, 
  AVG_RATING_SCORE, AVG_RATING_LABEL,
  GROWTH,
  SECTOR,
  NOTE
]
