from fields import *

OUTPUT_DIR = "output"
FILE_NAME = "JP.csv"
COLUMNS_TO_PRESERVE = [TICKER, BOUGHT]
FINAL_COLUMNS = [TICKER, NAME, BOUGHT, MARKET_CAP, PE_RATIO, FORWARD_PE_RATIO, PB, ROA, NET_MARGIN, OPERATING_MARGIN, DEBT_TO_EQUITY, EARNINGS_GROWTH, DIVIDEND_YIELD, VOL_1D, VOL_3D, VOL_5D, PRICE_1D, PRICE_3D, PRICE_5D, TARGET_HIGH_PERCENT, TARGET_LOW_PERCENT, TARGET_MEAN_PERCENT, CURRENT_PRICE, AVG_RATING, AVG_RATING_1D, AVG_RATING_7D, SECTOR]
