from fields import FAST, NORMAL, UPDATE_FINANCIALS, FILTER_ETFS, AGGREGATE_ETFS

FILE_NAME = "JP_ETFs.csv"
# FILE_NAME = "JP_ETFs_full.csv"
# FILE_NAME = "JP_stocks.csv"
# FILE_NAME = "US_stocks.csv"
FILE_NAME = "HK_stocks.csv"

SPEED = NORMAL
SPEED = FAST

MODE = UPDATE_FINANCIALS
# MODE = FILTER_ETFS
MODE = AGGREGATE_ETFS
